apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmmt-admin
  namespace: rmmt
  labels:
    app: rmmt-admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rmmt-admin
  template:
    metadata:
      labels:
        app: rmmt-admin
    spec:
      containers:
      - name: rmmt-admin
        image: rmmt-admin:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        env:
        - name: NUXT_API_URL
          value: "https://rmmt-api.rmmt.svc.cluster.local"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rmmt-admin
  namespace: rmmt
  labels:
    app: rmmt-admin
spec:
  selector:
    app: rmmt-admin
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 80
    protocol: TCP
  type: ClusterIP