---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rmmt-db-pv-volume
  namespace: rmmt
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/rmmt-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rmmt-db-pv-claim
  namespace: rmmt
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rmmt-db
  namespace: rmmt
  labels:
    app: rmmt-db
spec:
  serviceName: rmmt-db
  replicas: 1
  selector:
    matchLabels:
      app: rmmt-db
  template:
    metadata:
      labels:
        app: rmmt-db
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rmmt-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: rmmt-config
              key: DB_NAME
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: rmmt-config
              key: DB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rmmt-secrets
              key: DB_PASSWORD
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: rmmt-db-pv-volume
        persistentVolumeClaim:
          claimName: rmmt-db-pv-claim
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rmmt-db
  namespace: rmmt
  labels:
    app: rmmt-db
spec:
  selector:
    app: rmmt-db
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  type: ClusterIP